### PR TITLE
respect required signers in the transaction body

### PR DESCRIPTION
**Pull request by emiflake**
Previously, when a transaction that includes required signers in the body but doesn't necessarily include them in the inputs is being reviewed, the frontend doesn't acknowledge these.

Now, they are treated like any other required signature.

### CODE REVIEW

**Comment by emiflake** [comment]
Making it draft as I would like to test a little closer. Feel free to review, still.

**Comment by emiflake** [comment]
Alright, I did some testing. This works and supports both input-based required signatures as well as those present in the requiredSigners field. Submitting also works.

**Comment by siegfried** [comment]
Thanks. This wasn't added because I didn't have a TX to test because it is a TX of Plutus address usually. Could you share the TX you used? Also it might be better to separate these signers from the ones of key hashes on reviewing page. @emiflake

**Comment by emiflake** [comment]
> Thanks. This wasn't added because I didn't have a TX to test because it is a TX of Plutus address usually. Could you share the TX you used? Also it might be better to separate these signers from the ones of key hashes on reviewing page. @emiflake

I don't think separating them would make much sense. They shouldn't really be treated differently, since the ledger doesn't really do that. We could of course tag them somehow, but this can be implemented at a later PR.

**Review by siegfried — APPROVED** [review]

**Comment by siegfried** [comment]
Alright, I'll merge this. We can tag them later if we have to. Thanks again. @emiflake

**Comment by emiflake** [comment]
**For future reference**: here's an example transaction that requires multiple signatures that aren't necessarily present in the inputs.

```84aa008282582046ca7adbfd033214c24841a866f7c2560747a22b0a3dbb6977ab7d60bfb8a3a802825820ca644a4d89c0f4c287b7d323079ca4d179155677b11f172bf3a95f3fa4d6018f000182a300581d70ec949404a4230eeaae9f6584bbaeb640b0f8747dc08cc46cafebdd1501821a0014d8fea1581c9c7e835042480afcb9ac86dee71615a8e0dd65730994de98888869c7a14001028201d818584c9fd8799fd8799f9f581cc39f3e7eaca22b9b37a859031d8b585e5a92629518c40920728f9134581c1db147ca3695ae5a1080c9076d90119dfdc929c4bc1c112a6c1a13e3ff02ffffd87a80ff82581d602d1e75e9e1e9914746370b8a72e60f512daea1e213ac5bb8293870751a01aaa712021a000335950b5820875561de10c8592a842b939dcdb50f55a11a9a538371dd59c19847ddbd3945940d81825820c000ef227aed5a9cc721f8a29b9726122a23417d82cf59a175574be93cfff7f8080e82581cc39f3e7eaca22b9b37a859031d8b585e5a92629518c40920728f9134581c1db147ca3695ae5a1080c9076d90119dfdc929c4bc1c112a6c1a13e30f001082581d602d1e75e9e1e9914746370b8a72e60f512daea1e213ac5bb8293870751a030e24f8111a004c4b4012828258208148d6ec9c6e9c664e23ee34ad074cc881ed7e2c54c7d38dc00d9dfa075b47ca00825820ca644a4d89c0f4c287b7d323079ca4d179155677b11f172bf3a95f3fa4d6018f00a300818258207844e1498ae8b083062785b62b5d5743009fa56a910162a12aef7f340f98c7515840259e7cf23f8688bf2aad74cb78d63f8884d71a6fa838bc8eec079b2e4672c9370f0dbf421ac24094be52bd856f7103d3929ee04f25290bd998c723594c752a0e0480058184000100821a0003144e1a04835a70f5f6```

**Pull request merged**
